name: 'Contender Compare'
description: 'Runs flashbots/contender against two user-specified node binaries.'
inputs:
  contender_bin_main:
    description: 'Path to the contender binary.'
    required: false
    default: ''
  contender_bin_pr:
    description: 'Alternate contender binary; used for testing contender itself.'
    required: false
    default: ''
  contender_spam_args:
    description: "Raw args to pass to 'contender spam'"
    required: false
    default: '--tps 100 -d 5 erc20'
  node_bin_main:
    description: 'Path to the main branch node binary.'
    required: true
  node_args_main:
    description: 'Arguments to pass to the main branch node binary.'
    required: false
    default: ''
  node_bin_pr:
    description: 'Path to the PR branch node binary.'
    required: true
  node_args_pr:
    description: 'Arguments to pass to the PR branch node binary.'
    required: false
    default: ''
  rpc_main:
    description: "RPC URL of the main branch's EL node."
    required: false
    default: 'http://localhost:8545'
  rpc_pr:
    description: "RPC URL of the PR branch's EL node."
    required: false
    default: 'http://localhost:9545'

runs:
  using: 'composite'
  steps:
    - name: Install Foundry
      shell: bash
      run: |
        curl -L https://foundry.paradigm.xyz | bash
        ~/.foundry/bin/foundryup
        echo "$HOME/.foundry/bin" >> $GITHUB_PATH
    - name: Download contender binary if not provided
      shell: bash
      run: |
        if [ -z "${{ inputs.contender_bin_main }}" ]; then
          echo "Downloading latest contender release..."
          url=$(curl -s https://api.github.com/repos/flashbots/contender/releases/latest | grep browser_download_url | grep x86_64-unknown-linux | cut -d '"' -f 4 | head -n 1)
          curl -L "$url" -o contender.tar.gz
          tar -xzf contender.tar.gz
          contender_path=$(find . -type f -name 'contender' -executable | head -n 1)
          chmod +x "$contender_path"
          echo "contender_bin_main=$(pwd)/$contender_path" >> $GITHUB_ENV
        else
          echo "contender_bin_main=${{ inputs.contender_bin_main }}" >> $GITHUB_ENV
        fi
    - name: Run contender-compare
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/entrypoint.sh"
        "${{ github.action_path }}/entrypoint.sh"
      env:
        INPUT_CONTENDER_BIN_MAIN: "${{ env.contender_bin_main }}"
        INPUT_CONTENDER_BIN_PR: "${{ inputs.contender_bin_pr }}"
        INPUT_NODE_BIN_MAIN: "${{ inputs.node_bin_main }}"
        INPUT_NODE_ARGS_MAIN: "${{ inputs.node_args_main }}"
        INPUT_NODE_BIN_PR: "${{ inputs.node_bin_pr }}"
        INPUT_NODE_ARGS_PR: "${{ inputs.node_args_pr }}"
        INPUT_RPC_MAIN: "${{ inputs.rpc_main }}"
        INPUT_RPC_PR: "${{ inputs.rpc_pr }}"
        CONTENDER_SPAM_ARGS: "${{ inputs.contender_spam_args }}"

    - uses: actions/github-script@v7
      with:
        script: |
          const pr = context.payload.pull_request;
          if (!pr) core.setFailed("Not a PR context");

          const header = "<!-- contender-compare-report -->"; // sentinel
          const body = `${header}\n## Contender Report\n... your JSON → formatted ...`;

          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr.number,
          });

          const existing = comments.find(c => c.body?.includes(header));

          if (existing) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existing.id,
              body,
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body,
            });
          }
