name: 'Contender Compare'
description: 'Runs flashbots/contender against two user-specified node binaries.'
inputs:
  contender_bin_main:
    description: 'Path to the contender binary.'
    required: true
  contender_bin_pr:
    description: 'Alternate contender binary; used for testing contender itself.'
    required: false
    default: ''
  contender_spam_args:
    description: "Raw args to pass to 'contender spam'"
    required: false
    default: '--tps 100 -d 5 erc20'
  node_bin_main:
    description: 'Path to the main branch node binary.'
    required: true
  node_args_main:
    description: 'Arguments to pass to the main branch node binary.'
    required: false
    default: ''
  node_bin_pr:
    description: 'Path to the PR branch node binary.'
    required: true
  node_args_pr:
    description: 'Arguments to pass to the PR branch node binary.'
    required: false
    default: ''
  rpc_main:
    description: "RPC URL of the main branch's EL node."
    required: false
    default: 'http://localhost:8545'
  rpc_pr:
    description: "RPC URL of the PR branch's EL node."
    required: false
    default: 'http://localhost:9545'

runs:
  using: 'composite'
  steps:
    - name: Install Foundry
      shell: bash
      run: |
        curl -L https://foundry.paradigm.xyz | bash
        ~/.foundry/bin/foundryup
        echo "$HOME/.foundry/bin" >> $GITHUB_PATH
    - name: Run contender-compare
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/entrypoint.sh"
        "${{ github.action_path }}/entrypoint.sh"
      env:
        INPUT_CONTENDER_BIN_MAIN: "${{ inputs.contender_bin_main }}"
        INPUT_CONTENDER_BIN_PR: "${{ inputs.contender_bin_pr }}"
        INPUT_NODE_BIN_MAIN: "${{ inputs.node_bin_main }}"
        INPUT_NODE_ARGS_MAIN: "${{ inputs.node_args_main }}"
        INPUT_NODE_BIN_PR: "${{ inputs.node_bin_pr }}"
        INPUT_NODE_ARGS_PR: "${{ inputs.node_args_pr }}"
        INPUT_RPC_MAIN: "${{ inputs.rpc_main }}"
        INPUT_RPC_PR: "${{ inputs.rpc_pr }}"
        CONTENDER_SPAM_ARGS: "${{ inputs.contender_spam_args }}"
