name: 'Contender Compare'
description: 'Runs flashbots/contender against two user-specified node binaries.'
inputs:
  contender_bin:
    description: 'Path to the contender binary.'
    required: true
  node_main_bin:
    description: 'Path to the main branch node binary.'
    required: true
  node_main_args:
    description: 'Arguments to pass to the main branch node binary.'
    required: false
    default: ''
  node_pr_bin:
    description: 'Path to the PR branch node binary.'
    required: true
  node_pr_args:
    description: 'Arguments to pass to the PR branch node binary.'
    required: false
    default: ''
  rpc_main:
    description: "RPC URL of the main branch's EL node."
    required: false
    default: 'http://localhost:8545'
  rpc_pr:
    description: "RPC URL of the PR branch's EL node."
    required: false
    default: 'http://localhost:9545'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - name: Run contender-compare
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/entrypoint.sh"
        "${{ github.action_path }}/entrypoint.sh" "$INPUT_CONTENDER_BIN" "$INPUT_BINARY_MAIN" "$INPUT_BINARY_MAIN_ARGS" "$INPUT_BINARY_PR" "$INPUT_BINARY_PR_ARGS" "$INPUT_RPC_MAIN" "$INPUT_RPC_PR"
      env:
        INPUT_CONTENDER_BIN: ${{ inputs.contender_bin }}
        INPUT_BINARY_MAIN: ${{ inputs.node_main_bin }}
        INPUT_BINARY_MAIN_ARGS: ${{ inputs.node_main_args }}
        INPUT_BINARY_PR: ${{ inputs.node_pr_bin }}
        INPUT_BINARY_PR_ARGS: ${{ inputs.node_pr_args }}
        INPUT_RPC_MAIN: ${{ inputs.rpc_main }}
        INPUT_RPC_PR: ${{ inputs.rpc_pr }}
